// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKVRKNzknZyE2o9a8oQDelqD0cZ5eAZPo',
    appId: '1:650834573158:web:85368dbbddf198dd4c7aa7',
    messagingSenderId: '650834573158',
    projectId: 'todo-bloc-f7252',
    authDomain: 'todo-bloc-f7252.firebaseapp.com',
    storageBucket: 'todo-bloc-f7252.appspot.com',
    measurementId: 'G-8F18FTPJGQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBO2pai8vNFymTlqgJjc945jQeIxzsaoqs',
    appId: '1:650834573158:android:e9a015b8a89126c54c7aa7',
    messagingSenderId: '650834573158',
    projectId: 'todo-bloc-f7252',
    storageBucket: 'todo-bloc-f7252.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZ1B1RGgaEGR6mzrX6wQnaK55gAhsenjE',
    appId: '1:650834573158:ios:a9dc486a25c4c9fb4c7aa7',
    messagingSenderId: '650834573158',
    projectId: 'todo-bloc-f7252',
    storageBucket: 'todo-bloc-f7252.appspot.com',
    iosClientId: '650834573158-tf6g8eu6841qbmf5rbl4v7qm0t6njpcv.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterBlocExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZ1B1RGgaEGR6mzrX6wQnaK55gAhsenjE',
    appId: '1:650834573158:ios:a9dc486a25c4c9fb4c7aa7',
    messagingSenderId: '650834573158',
    projectId: 'todo-bloc-f7252',
    storageBucket: 'todo-bloc-f7252.appspot.com',
    iosClientId: '650834573158-tf6g8eu6841qbmf5rbl4v7qm0t6njpcv.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterBlocExample',
  );
}
